src/AppBundle/Entity/Consulta.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Visita
 *
 * @ORM\Table(name="consulta")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ConsultaRepository")
 * * @UniqueEntity( fields={"usuario","usuarioRegistro","dia","mes","anno","horaInicial","horaFinal","minutoInicial","minutoFinal"}, message="Ya existe una consulta con el mismo medico en la fecha seleccionada." )
 */
class Consulta {

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Especialidad", inversedBy="consulta")
     * @ORM\JoinColumn(
     *     name="id_especialidad",
     *     referencedColumnName="id",
     *     nullable=false
     * )
     */
    private $especialidad;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Estado", inversedBy="consulta")
     * @ORM\JoinColumn(
     *     name="id_estado",
     *     referencedColumnName="id",
     *     nullable=false
     * )
     */
    private $estado;

    /**
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\Evolucion", mappedBy="consulta")
     */
    private $evolucion;

    /**
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\FacturaConsulta", mappedBy="consulta")
     */
    private $factura;

    /**
     * @var float
     *
     * @ORM\Column(type="integer",options={"default":1})
     */
    private $tipoConsulta = 1;

    /**
     * @var \DateTime
     *
     * @ORM\Column type="datetime",nullable=true)
     *
     */
    private $fechaCompleta;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Usuario", inversedBy="consulta")
     * @ORM\JoinColumn(
     *     name="id_medico",
     *     referencedColumnName="id",
     *     nullable=false
     * )
     */
    private $usuario;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Usuario", inversedBy="consultaRegistro")
     * @ORM\JoinColumn(
     *     name="id_usuario_registro",
     *     referencedColumnName="id",
     *     nullable=false
     * )
     */
    private $usuarioRegistro;

    /**
     * @var \DateTime
     *
     * @ORM\Column type="integer")
     *
     */
    private $dia;

    /**
     *
     *
     * @ORM\Column type="integer")
     *
     */
    private $mes;

    /**
     *
     *
     * @ORM\Column type="integer")
     *
     */
    private $anno;

    /**
     *
     *
     * @ORM\Column type="integer")
     *
     */
    private $horaInicial;

    /**
     *
     *
     * @ORM\Column type="integer")
     *
     */
    private $horaFinal;

    /**
     *
     *
     * @ORM\Column type="integer")
     *
     */
    private $minutoInicial;

    /**
     *
     *
     * @ORM\Column type="integer")
     *
     */
    private $minutoFinal;

    /**
     * @var string
     *
     * @ORM\Column(name="mensaje", type="text", length=255,nullable=true)
     */
    private $mensaje;

    public function getDataToEmail() {
        return 'por el usuario con nombre ' . $this->getUsuarioRegistro()->getCompleteName() . ' para la fecha ' . $this->completeZero($this->getDia()) . '/' . ($this->getMes()) . '/' . $this->getAnno() . ' y la hora ' . $this->getHoraInicialC() . ':' . $this->getMinutoInicialC();
    }

    public function getDataDate() {
        return ($this->getMes()) . '/' . $this->completeZero($this->getDia()) . '/' . $this->getAnno() . ' ' . $this->getHoraInicialC() . ':' . $this->getMinutoInicialC();
    }

    public function getDataToEmailClient() {
        return ' para la fecha ' . $this->completeZero($this->getDia()) . '/' . $this->getMes() . '/' . $this->getAnno() . ' y la hora ' . $this->getHoraInicialC() . ':' . $this->getMinutoInicialC() . ' y ha seleccionado como doctor a:' . $this->getUsuario()->getCompleteName() . ' en la especialidad de ' . $this->getEspecialidad()->getNombre() . '.';
    }

    public function getDataToEmailClientAprobbed() {
        return ' para la fecha ' . $this->completeZero($this->getDia()) . '/' . $this->getMes() . '/' . $this->getAnno() . ' y la hora ' . $this->getHoraInicialC() . ':' . $this->getMinutoInicialC() . ' y  como doctor a:' . $this->getUsuario()->getCompleteName() . ' en la especialidad de ' . $this->getEspecialidad()->getNombre() . '.';
    }

    public function getDateClientAprobbed() {
        return ' ' . $this->completeZero($this->getDia()) . '/' . $this->getMes() . '/' . $this->getAnno() . ' a las ' . $this->getHoraInicialC() . ':' . $this->getMinutoInicialC() . '  con el doctor: ' . $this->getUsuario()->getCompleteName() . ' en la especialidad de ' . $this->getEspecialidad()->getNombre() . '.';
    }

    public function getHoraInicialC() {
        return $this->completeZero($this->horaInicial);
    }

    public function getHoraFinalC() {
        return $this->completeZero($this->horaFinal);
    }

    public function getMinutoInicialC() {
        return $this->completeZero($this->minutoInicial);
    }

    public function getMinutoFinalC() {
        return $this->completeZero($this->minutoFinal);
    }

    private function completeZero($value) {
        if ($value < 10)
            return '0' . $value;
        return $value;
    }

    /**
     * Set resultado
     *
     * @param \AppBundle\Entity\ResultadoConsulta $resultado
     * @return Consulta
     */
    public function setResultado(\AppBundle\Entity\ResultadoConsulta $resultado = null) {
        $this->resultado = $resultado;

        return $this;
    }

    /**
     * Get resultado
     *
     * @return \AppBundle\Entity\ResultadoConsulta
     */
    public function getResultado() {
        return $this->resultado;
    }

    /**
     * Set factura
     *
     * @param \AppBundle\Entity\FacturaConsulta $factura
     * @return Consulta
     */
    public function setFactura(\AppBundle\Entity\FacturaConsulta $factura = null) {
        $this->factura = $factura;

        return $this;
    }

    /**
     * Get factura
     *
     * @return \AppBundle\Entity\FacturaConsulta
     */
    public function getFactura() {
        return $this->factura;
    }

    public function getDataToTemplate() {
        return ' ' . $this->getDia() . '/' . $this->getMes() . '/' . $this->getAnno() . ' ' . $this->getHoraInicialC() . ':' . $this->getMinutoInicialC();
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->servicio = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add servicio
     *
     * @param \AppBundle\Entity\Servicio $servicio
     * @return Consulta
     */
    public function addServicio(\AppBundle\Entity\Servicio $servicio) {
        $this->servicio[] = $servicio;

        return $this;
    }

    /**
     * Remove servicio
     *
     * @param \AppBundle\Entity\Servicio $servicio
     */
    public function removeServicio(\AppBundle\Entity\Servicio $servicio) {
        $this->servicio->removeElement($servicio);
    }

    /**
     * Get servicio
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getServicio() {
        return $this->servicio;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set dia
     *
     * @param string $dia
     * @return Consulta
     */
    public function setDia($dia) {
        if ($dia < 10) {
            $dia = '0' . $dia;
        }
        $this->dia = $dia;

        return $this;
    }

    /**
     * Get dia
     *
     * @return string
     */
    public function getDia() {
        return $this->dia;
    }

    public function getDiaWithZero() {
       return $this->completeZero($this->getDia());
    }

    /**
     * Set mes
     *
     * @param string $mes
     * @return Consulta
     */
    public function setMes($mes) {
        $this->mes = $mes;

        return $this;
    }

    /**
     * Get mes
     *
     * @return string
     */
    public function getMes() {
        return $this->mes;
    }

    /**
     * Set anno
     *
     * @param string $anno
     * @return Consulta
     */
    public function setAnno($anno) {
        $this->anno = $anno;

        return $this;
    }

    /**
     * Get anno
     *
     * @return string
     */
    public function getAnno() {
        return $this->anno;
    }

    /**
     * Set horaInicial
     *
     * @param string $horaInicial
     * @return Consulta
     */
    public function setHoraInicial($horaInicial) {
        $this->horaInicial = $horaInicial;

        return $this;
    }

    /**
     * Get horaInicial
     *
     * @return string
     */
    public function getHoraInicial() {
        return $this->horaInicial;
    }

    /**
     * Set horaFinal
     *
     * @param string $horaFinal
     * @return Consulta
     */
    public function setHoraFinal($horaFinal) {
        $this->horaFinal = $horaFinal;

        return $this;
    }

    /**
     * Get horaFinal
     *
     * @return string
     */
    public function getHoraFinal() {
        return $this->horaFinal;
    }

    /**
     * Set minutoInicial
     *
     * @param string $minutoInicial
     * @return Consulta
     */
    public function setMinutoInicial($minutoInicial) {
        $this->minutoInicial = $minutoInicial;

        return $this;
    }

    /**
     * Get minutoInicial
     *
     * @return string
     */
    public function getMinutoInicial() {
        return $this->minutoInicial;
    }

    /**
     * Set minutoFinal
     *
     * @param string $minutoFinal
     * @return Consulta
     */
    public function setMinutoFinal($minutoFinal) {
        $this->minutoFinal = $minutoFinal;

        return $this;
    }

    /**
     * Get minutoFinal
     *
     * @return string
     */
    public function getMinutoFinal() {
        return $this->minutoFinal;
    }

src/AppBundle/Resources/views/Client/date_register.html.twig
{% if daysSelected ==null and (app.user.rol.id==1 or app.user.rol.id==3)%}

    <script>


        {% if daysSelected ==null%}
        toastr.options = {
            closeButton: true,
            progressBar: true,
            showMethod: 'slideDown',
            timeOut: 2000
        };
        toastr.warning('', 'No existen consultas planificadas para la fecha seleccionada.');
        {% endif %}

    </script>

{% else %}
        <h4 class="center-block">Día de la consulta: </h4>
        <table class="table table-bordered">

            <thead>
            <th>Dom</th>
            <th>Lun</th>
            <th>Mar</th>
            <th>Mie</th>
            <th>Jue</th>
            <th>Vie</th>
            <th>Sab</th>

            </thead>
            {% set cont =1 %}
            {% for i in 0.. totalWeek-1 %}
                <tr>
                    {% for j in 0..6 %}
                        {% if (j==day and  cont <= totalDays)or (cont > 1 and cont <= totalDays) %}
                            {% set include=false %}
                            {% if daysSelected and (cont in daysSelected ) %}
                                {% set include=true %}
                            {% endif %}

                            <td td-val="{{ cont }}" class="  {% if include %} btn-primary{% endif %}"
                                {% if include %}style="padding:2px;!important ;cursor: pointer;" id="td-{{ cont }}"
                                onclick="check(this)" {% else %} style="padding:2px;"{% endif %}>&nbsp;&nbsp;{{ cont }}

                                &nbsp;&nbsp;{% if include %}
                                <i id="a-td-{{ cont }}" class="fa fa-check p-w-3"></i>
                                <div style="margin-top: 10px">
                                    {% for key,value in countQuery %}
                                        {% if key==cont %}
                                            <i class="fa fa-users">&nbsp;&nbsp;{{ value }}</i>  &nbsp;
                                        {% endif %}

                                    {% endfor %}
                                </div>
                                <div style="margin-top: 10px">
                                    {% for key,value in clocks %}
                                        {% if key==cont %}
                                            <i class="fa fa-clock-o"> {{ value.min }}-{{ value.max }}</i>&nbsp;&nbsp; &nbsp;
                                        {% endif %}

                                    {% endfor %}

                                    {% endif %}
                                </div>
                                &nbsp;</td>


                            {% set cont= cont+1 %}
                        {% else %}
                            <td>&nbsp;&nbsp;&nbsp;</td>
                        {% endif %}


                    {% endfor %}
                </tr>
            {% endfor %}
        </table>

{% endif %}

src/AppBundle/Resources/views/Client/edit_client_user.html.twig
{% extends 'base.html.twig' %}
{% block css %}
    {{ parent() }}
    <link href="{{asset('bundles/app/css/plugins/chosen/bootstrap-chosen.css')}}" rel="stylesheet">
    <link href="{{asset('bundles/app/css/plugins/touchspin/jquery.bootstrap-touchspin.min.css')}}" rel="stylesheet">
{% endblock %}
{% block content %}

    <h3 class="center-block">Actualizar perfil  </h3>
    <div class="panel  panel-primary"></div>
    {% set idUser= id%}
        <form class="m-t" role="form" action="{{ path('manage_perfil_client_user_edit',{id:idUser}) }}" id="form-user" method="POST">

            <div class="row">
                {% if exception is defined %}
                    <div class="form-group has-error">{{ exception  }} </div>
                {% endif %}
                <div class="col-lg-12">
                    <div class="col-lg-4">

                        {% if errors and errors.nombre is defined %}
                        <div class="form-group has-error">
                            <span class="help-block">
                                        <strong>{{ errors['nombre'] }}</strong>
                                    </span>
                            {% else %}
                            <div class="form-group">
                                {% endif %}
                                <label>Nombre</label>
                                <input type="text" {% if data and data.nombre %}
                                    value="{{ data.nombre }}"
                                {% endif %} class="form-control" name="nombre" placeholder="Nombre" required="">
                            </div>
                            {% if errors and errors.apellido is defined%}
                            <div class="form-group has-error">
                            <span class="help-block">
                                        <strong>{{ errors['apellido'] }}</strong>
                                    </span>
                                {% else %}
                                <label>Apellidos</label>
                                <div class="form-group">
                                    {% endif %}
                                    <input type="text" {% if data and data.apellido%}
                                        value="{{ data.apellido }}"
                                    {% endif %} class="form-control" name="apellido" placeholder="Apellidos"
                                           required="">
                                </div>
                                {% if errors and errors.edad is defined %}
                                <div class="form-group has-error">
                            <span class="help-block">
                                        <strong>{{ errors['edad'] }}</strong>
                                    </span>
                                    {% else %}
                                    <div class="form-group">
                                        {% endif %}
                                        <label>Edad</label>
                                        <input type="text" {% if data and data.edad %}
                                            value="{{ data.edad }}"
                                        {% endif %} class="form-control touchspin3" name="edad" placeholder="Edad" required="">
                                    </div>

                                    {% if errors and errors.direccion is defined %}
                                    <div class="form-group has-error">
                            <span class="help-block">
                                        <strong>{{ errors['direccion'] }}</strong>
                                    </span>
                                        {% else %}
                                        <div class="form-group">
                                            {% endif %}
                                            <label>Dirección</label>
                                            <input type="text" {% if data and data.direccion %}
                                                value="{{ data.direccion }}"
                                            {% endif %} class="form-control" name="direccion"
                                                   placeholder="Dirección"
                                            >
                                        </div>
                                    </div>



                                    <div class="col-lg-4">
                                        {% if errors and errors.cedula is defined %}
                                        <div class="form-group has-error">
                            <span class="help-block">
                                        <strong>{{ errors['cedula'] }}</strong>
                                    </span>
                                            {% else %}
                                            <div class="form-group">
                                                {% endif %}
                                                <label>Cédula</label>
                                                <input alt="Cédula" type="text" class="form-control"
                                                        {% if data and data.cedula %}
                                                            value="{{ data.cedula }}"
                                                        {% endif %}
                                                       name="cedula" data-mask="9999999999-9" placeholder="Cédula">
                                            </div>



                                        {% if errors and errors.telefono is defined %}
                                        <div class="form-group has-error">
                            <span class="help-block">
                                        <strong>{{ errors['telefono'] }}</strong>
                                    </span>
                                            {% else %}
                                            <div class="form-group">
                                                {% endif %}
                                                <label>Teléfono</label>
                                                <input type="text" {% if data and data.telefono %}
                                                    value="{{ data.telefono }}"
                                                {% endif %} class="form-control" name="telefono"
                                                       data-mask="99-9999-9999" placeholder="Teléfono"
                                                       required="">
                                            </div>


                                            {% if errors and errors.telefonoConvencional is defined %}
                                            <div class="form-group has-error">
                            <span class="help-block">
                                        <strong>{{ errors['telefonoConvencional'] }}</strong>
                                    </span>
                                                {% else %}
                                                <div class="form-group">
                                                    {% endif %}
                                                    <label>Teléfono convencional</label>
                                                    <input type="text" {% if data and data.telefonoConvencional%}
                                                        value="{{ data.telefonoConvencional}}"
                                                    {% endif %} class="form-control" name="telefonoConvencional"
                                                           data-mask="99-9999999" placeholder="Teléfono convencional"
                                                    >
                                                </div>


                                        </div>







                          <div  class="col-lg-4">



                                        {% if errors and errors.nombreUsuario is defined %}
                                        <div class="form-group has-error">
                            <span class="help-block">
                                        <strong>{{ errors['nombreUsuario'] }}</strong>
                                    </span>
                                            {% else %}
                                            <div class="form-group">
                                                {% endif %}
                                                <label>Nombre de usuario</label>
                                                <input type="text" {% if data and data.nombreUsuario is defined %}
                                                    value="{{ data.nombreUsuario }}"
                                                {% endif %} id="nombreUsuario" class="form-control" name="nombreUsuario"
                                                       placeholder="Nombre de usuario"
                                                       required="">
                                            </div>
                                            {% if errors and errors.password is defined %}
                                            <div class="form-group has-error">
                            <span class="help-block">
                                        <strong>{{ errors['password'] }}</strong>
                                    </span>
                                                {% else %}
                                                <div class="form-group">
                                                    {% endif %}
                                                    <label>Contraseña</label>
                                                    <input type="password" {% if data and data.password  %}
                                                        value=""
                                                    {% endif %} class="form-control" name="password"
                                                           placeholder="Contraseña"
                                                           >
                                                </div>



                                                {% if errors and errors.correo is defined %}
                                                <div class="form-group has-error">
                            <span class="help-block">
                                        <strong>{{ errors['correo'] }}</strong>
                                    </span>
                                                    {% else %}
                                                    <div class="form-group">
                                                        {% endif %}
                                                        <label>Correo</label>
                                                        <input type="email" {% if data and data.correo%}
                                                            value="{{ data.correo}}"
                                                        {% endif %} class="form-control" name="correo" placeholder="Correo" required="">
                                                    </div>

                                        </div>

                                        <div class="form-group">


                                            <div class="col-lg-offset-9">


                                                <button type="submit" class=" btn btn-primary">Aceptar</button>
                                                <a href="{{ path('manage') }}" class=" btn btn-warning">Volver al inicio</a>
                                            </div>
                                        </div>


        </form>
    </div>


<!-- Mainly scripts -->
<script src="{{ asset('bundles/app/js/jquery-2.1.1.js') }}"></script>
<script src="{{ asset('bundles/app/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('bundles/app/js/plugins/jasny/jasny-bootstrap.min.js') }}"></script>

    <script src="{{ asset('bundles/app/js/plugins/touchspin/jquery.bootstrap-touchspin.min.js') }}"></script>

<script src="{{ asset('bundles/app/js/plugins/bootstrap-tagsinput/bootstrap-tagsinput.js') }}"></script>


    <script src="{{asset('bundles/app/js/plugins/validation/jquery.validationEngine.js')}}"></script>


    <script src="{{asset('bundles/app/js/plugins/validation/jquery.validate.min.js')}}"></script>

    <script src="{{asset('bundles/app/js/plugins/validation/additionalValidator.js')}}"></script>
<script>
id_user={{ idUser }}
    $(document).ready(function () {

        $('.tagsinput').tagsinput({
            tagClass: 'label label-primary'
        });
        $(".touchspin3").TouchSpin({
            verticalbuttons: true,
            buttondown_class: 'btn btn-white',
            buttonup_class: 'btn btn-white',
            max:120,
            min:1
        });

    })</script>
    {{ parent() }}

    <script src="{{ asset('bundles/app/js/custom/validationUser.js') }}"></script>
    <script>
        $(function () { formUserValidation(2,false); });
    </script>
{% endblock %}

src/AppBundle/Resources/views/Client/list_query_executed.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <div>


<h3>Listado de consultas realizadas</h3>
        <div class="panel  panel-primary"></div>



    </div>
    <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover dataTables-example" >
    <thead>
    <tr>
        <th>Especialidad </th>
        <th>Nombre del Doctor</th>
        <th>Fecha de la consulta</th>
        <th>Hora inicial</th>
        <th>Hora final</th>
        <th>Precio</th>

    </tr>
    </thead>
    <tbody>
    {% for esp in especialities %}
        <tr>

           <td>{{ esp.especialidad.nombre }}</td>
           <td>{{ esp.usuario.getCompleteName() }}</td>
           <td>{{ esp.dia }}/{{ esp.mes }}/{{ esp.anno }}</td>
           <td>{{ esp.horaInicialC }}:{{ esp.minutoInicialC }}</td>
           <td>{{ esp.horaFinalC }}:{{ esp.minutoFinalC }}</td>
           {% if esp.factura %}
               <td>${{ esp.factura.getValueTotal() }}</td>
           {% else %}
               <td>Pendiente de factura</td>
           {% endif %}





        </tr>
        {% endfor %}
    </tbody>
</table>

    {{ parent() }}
    {% include 'AppBundle:Default:show_datatable_message.js.twig' %}
{% endblock %}

src/AppBundle/Resources/views/Client/list_reserved.html.twig
{% extends 'base.html.twig' %}
{% block css %}
    {{ parent() }}
    <link href="{{ asset('bundles/app/css/plugins/sweetalert/sweetalert.css') }}" rel="stylesheet">



{% endblock %}


{% block content %}

    <div>


        <h3>Listado de reservaciones realizadas</h3>
        <div class="panel  panel-primary"></div>
        <a href="{{ path('client_query_register') }}" title="Registrar una reservación"
           class="btn btn-primary btn-circle pull-right" type="button"><i class="fa fa-plus"></i>
        </a>

    </div>
    <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover dataTables-example">
        <thead>
        <tr>
            <th>Especialidad</th>
            <th>Nombre del Doctor</th>
            <th>Fecha de la consulta</th>
            <th>Hora inicial</th>
            <th>Hora final</th>
            <th>Estado de la reserva</th>

            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        {% for esp in especialities %}
            <tr>

                <td>{{ esp.especialidad.nombre }}</td>
                <td>{{ esp.usuario.getCompleteName() }}</td>
                <td>{{ esp.dia }}/{{ esp.mes }}/{{ esp.anno }}</td>
                <td>{{ esp.horaInicialC }}:{{ esp.minutoInicialC }}</td>
                <td>{{ esp.horaFinalC }}:{{ esp.minutoFinalC }}</td>
                <td>{{ esp.estado.nombre }}</td>

                <td>

                    {% if  esp.estado.id ==1 %}
                        <a title="Actualizar reservación" class="btn btn-info btn-circle"
                           href="{{ path('cliente_query_update',{id:esp.id}) }}"
                           type="button"><i class="fa fa-check"></i>
                        </a>


                        <a
                           data-record-id="{{ path('client_query_cancel',{id:esp.id}) }}"
                           class="btn btn-warning btn-circle demo3" title="Cancelar reservación" href="#"><i
                                    class="fa fa-ban"></i>
                        </a>

                    {% endif %}
                     {% if esp.estado.id==4 and esp.factura is not null  %}

                <a  title="Visualizar factura digital" class="btn btn-info btn-circle" href="{{ path('manage_check_client_pdf_generate',{id:esp.factura.id}) }}"
                  type="button"><i class="fa fa-file-pdf-o"></i>
               </a>
                  {% endif %}
                </td>


            </tr>
        {% endfor %}
        </tbody>
    </table>

    {{ parent() }}
    {% include 'AppBundle:Default:show_datatable_message.js.twig' %}
{% endblock %}
        {% block javascript %}

    {{ parent() }}

    <script src="{{ asset('bundles/app/js/plugins/sweetalert/sweetalert.min.js') }}"></script>
    <script>

    $(document).ready(function () {



        $('.demo3').click(function (e) {
            var url = $(this).data('recordId');

            swal({
                title:'',
                text: "¿Está seguro que desea cancelar la reservación?",
                type: "warning",
                showCancelButton: true,
                cancelButtonColor: "#18a689",
                confirmButtonColor: "#ed5565",
                confirmButtonText: "Aceptar",
                cancelButtonText: "Cancelar",
                closeOnConfirm: true
            }, function () {

                 waitMeShow();
                 window.location.href=url;
            });
        });
        })
        </script>
{% endblock javascript %}